### ISSUE TITLE
pth파일 안써짐

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/YOLO#20]
Traceback (most recent call last):
  File "train.py", line 205, in <module>
    torch.save(model.state_dict(), f"weights/custom/yolov4_custom_{round(AP.mean(), 3)}.pth")
  File "/home/minji/.local/lib/python3.6/site-packages/torch/serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/minji/.local/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/minji/.local/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'weights/custom/yolov4_custom_0.182.pth'

**Comment by minji-o-j** [comment]
weights안에 custom폴더는 만들어줘야한다.
